[package]
name = "norm"
version = "0.1.1"
edition = "2021"
description = "A collection of distance metrics on strings"
repository = "https://github.com/nomad/norm"
license = "MIT"

[dependencies]
memchr = "2"
wasm-bindgen = "0.2.95"
console_error_panic_hook = "0.1.7"

[lib]
crate-type = ["cdylib"]